import urllib.request
import urllib.parse
import json
import os

# Try to import the Google GenAI SDK
try:
    from google import genai
    from google.genai import types
except ImportError:
    print("Dependencies missing. Please install the Google GenAI SDK first:")
    print("pip install google-genai")
    exit(1)

# --- CONFIGURATION ---
# The actual Page ID for The Digital Retreat
PAGE_ID = "1067002106506552"

# Use the User Access Token you got from the browser
USER_ACCESS_TOKEN = "EAANYxhlWhAcBRoZAZCawZB9jC9SOEBQSejhOjZCefnfmSwZAoNkcx9tsFZAQeXkNRbW5KGqSM9JoJcOZC7itrzGyvYQUyjPoThNiUmQGIHKO4dl8EWktbNiZCJqFi46ZAdYr7My4JZATk8OTuuUwY4yAuqjfr1Ch1PV5hyuJ4MJRNBa8L81GgeYnHZA89LHXrRuP1RseXLO2R3mlmPOZBKATZBoaSuQlJcwdFkZCgfG4d7ZAaiqVBhxAeLLXHqnzLQd92GJiZA5pymI0ZBZB7oB7OLVS0knVmEgQIyzwZDZD"

# Prompt for the image you want Gemini (Imagen 3) to generate
IMAGE_PROMPT = "A futuristic digital sanctuary, high-tech cozy cabin with neon blue accents, serene ambiance, minimalist, 4k"

# Caption for the Facebook post
POST_CAPTION = "Generated with Gemini (Imagen 3) and automatically posted via Python! 🤖🎨"
# ---------------------

def get_page_access_token():
    print("Fetching Page Access Token...")
    accounts_url = f"https://graph.facebook.com/v25.0/me/accounts?access_token={USER_ACCESS_TOKEN}"
    try:
        req = urllib.request.Request(accounts_url)
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode())
            for page in data.get("data", []):
                if str(page["id"]) == PAGE_ID:
                    print(f"Found Page: {page['name']}")
                    return page["access_token"]
    except Exception as e:
        print(f"Error fetching page access token: {e}")
    return None

def generate_image_with_gemini(prompt: str) -> bytes:
    # Ensure GEMINI_API_KEY environment variable is set
    if not os.environ.get("GEMINI_API_KEY"):
        print("\n❌ Error: GEMINI_API_KEY environment variable is not set.")
        print("Please set it in your terminal:")
        print('Windows (PowerShell): $env:GEMINI_API_KEY="your_api_key"')
        exit(1)

    print(f"Generating image using Gemini (Imagen 3) for prompt: '{prompt}'...")
    client = genai.Client()
    
    # Generate image using Imagen 3 model
    result = client.models.generate_images(
        model='imagen-3.0-generate-002',
        prompt=prompt,
        config=types.GenerateImagesConfig(
            number_of_images=1,
            output_mime_type="image/png",
            aspect_ratio="1:1"
        )
    )
    
    # Get the raw bytes of the generated image
    for generated_image in result.generated_images:
        return generated_image.image.image_bytes
    
    raise Exception("No image was generated by Gemini.")

def post_image_to_facebook(page_token: str, image_bytes: bytes, caption: str):
    print("Uploading generated image to Facebook Page...")
    
    boundary = "----WebKitFormBoundary7MA4YWxkTrZu0gW"
    parts = []
    
    # Add caption
    parts.append(f"--{boundary}".encode('utf-8'))
    parts.append('Content-Disposition: form-data; name="caption"'.encode('utf-8'))
    parts.append(''.encode('utf-8'))
    parts.append(caption.encode('utf-8'))
    
    # Add access_token
    parts.append(f"--{boundary}".encode('utf-8'))
    parts.append('Content-Disposition: form-data; name="access_token"'.encode('utf-8'))
    parts.append(''.encode('utf-8'))
    parts.append(page_token.encode('utf-8'))
    
    # Add photo file (from memory bytes)
    parts.append(f"--{boundary}".encode('utf-8'))
    parts.append(f'Content-Disposition: form-data; name="source"; filename="gemini_generated.png"'.encode('utf-8'))
    parts.append('Content-Type: image/png'.encode('utf-8'))
    parts.append(''.encode('utf-8'))
    parts.append(image_bytes)
    
    # End boundary
    parts.append(f"--{boundary}--".encode('utf-8'))
    
    body = b"\r\n".join(parts)
    
    post_url = f"https://graph.facebook.com/v25.0/{PAGE_ID}/photos"
    
    req = urllib.request.Request(post_url, data=body, method="POST")
    req.add_header('Content-Type', f'multipart/form-data; boundary={boundary}')
    req.add_header('Content-Length', str(len(body)))
    
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode())
            print(f"\n✅ Success! Photo posted to Page.")
            print(f"Post ID: {res_data.get('post_id')}")
            print(f"View it here: https://facebook.com/{res_data.get('post_id')}")
    except urllib.error.URLError as e:
        print(f"\n❌ Error uploading photo: {e}")
        if hasattr(e, 'read'):
            print(e.read().decode())

def main():
    # 1. Fetch Page Token
    page_token = get_page_access_token()
    if not page_token:
        print("Failed to get Page access token.")
        return
        
    # 2. Generate Image using Gemini (Imagen 3)
    try:
        image_bytes = generate_image_with_gemini(IMAGE_PROMPT)
    except Exception as e:
        print(f"Error generating image: {e}")
        return

    # 3. Save a local copy for records
    local_path = "gemini_output.png"
    with open(local_path, "wb") as f:
        f.write(image_bytes)
    print(f"Saved local copy of the image to {os.path.abspath(local_path)}")

    # 4. Post to Facebook
    post_image_to_facebook(page_token, image_bytes, POST_CAPTION)

if __name__ == "__main__":
    main()
